In [1]:
import csv

In [2]:
from time import strptime

In [3]:
import pandas as pd

In [4]:
from geojson import Feature, FeatureCollection, Point

In [5]:
import json

In [11]:
import numpy as np

In [7]:
filepath = './xls_datasets/map_3.xlsx'

In [8]:
workbook = pd.ExcelFile(filepath)
sheets = workbook.sheet_names

df = pd.concat([pd.read_excel(workbook, sheet_name=s)
                .assign(sheet_name=s) for s in sheets], ignore_index=True)

In [9]:
df.tail(5)

,coordinates,day,month,sheet_name,type,scale,description
415,"46.959077, 32.011810",18,July,Цивільна інфраструктура,point,NaN,У Миколаєві ракети влучили в автосалон та сало...
416,"47.041280, 32.438662",22,July,Цивільна інфраструктура,point,NaN,Влучання в будівлю магазину та гаражний коопер...
417,"46.959077, 32.011812",28,July,Цивільна інфраструктура,point,NaN,Ракетний удар по Миколаєву пошкодив яхт-клуб.
418,"46.959077, 32.011812",28,July,Цивільна інфраструктура,point,NaN,У Миколаєві пошкоджено пункт видачі гуманітарн...
419,"46.959077, 32.011812",31,July,Цивільна інфраструктура,point,NaN,Внаслідок масованих обстрілів Миколаєва пошкод...

In [10]:
df = df.dropna(subset=['day']) # dropping all Null values in column

In [11]:
df.loc[df['scale'].notnull()]

,coordinates,day,month,sheet_name,type,scale,description
227,"47.090263, 32.448873",1,July,Загиблі цивільні,NaN,1.0,"В с. Білозірка пошкоджено будинок, загинула од..."
228,"46.826064, 32.219268",2,July,Загиблі цивільні,NaN,1.0,В селищі Луч внаслідок ворожих обстрілів загин...
229,"47.023995, 32.427847",5,July,Загиблі цивільні,NaN,1.0,Внаслідок обстрілів с. Засілля загинула одна л...
230,"46.942736, 31.552642",6,July,Загиблі цивільні,NaN,1.0,Під час обстрілів с. Нечаяне загинула одна люд...
231,"46.824849, 32.141298",7,July,Загиблі цивільні,NaN,2.0,Внаслідок обстрілів с. Українка Галицинівської...
232,"47.403720, 32.438221",12,July,Загиблі цивільні,NaN,1.0,Через ракетний удар по Баштанці загинула жінка.
233,"46.999938, 32.395752",13,July,Загиблі цивільні,NaN,4.0,Через обстріли с. Новоселівка загинуло 4 людини.
234,"47.403720, 32.438221",14,July,Загиблі цивільні,NaN,1.0,Через нічний обстріл Баштанки загинула одна лю...
235,"46.862150, 32.196443",16,July,Загиблі цивільні,NaN,3.0,У с. Шевченкове внаслідок обстрілів загинули т...
236,"47.123866, 32.621648",16,July,Загиблі цивільні,NaN,1.0,Через обстріли у Широківській громаді загинула...
237,"47.098634, 32.674144",21,July,Загиблі цивільні,NaN,1.0,В с. Широке внаслідок влучання боєприпасу в жи...
238,"46.862150, 32.196443",23,July,Загиблі цивільні,NaN,2.0,Через удари по с. Шевченкове загинуло дві людини.
239,"46.959077, 32.011812",29,July,Загиблі цивільні,NaN,7.0,Ворожі касетні снаряди влучили у зупинку грома...
240,"46.959077, 32.011812",30,July,Загиблі цивільні,NaN,1.0,У Миколаєві обстріляли один зі спальних районі...
241,"46.959077, 32.011812",31,July,Загиблі цивільні,NaN,1.0,Внаслідок масованих обстрілів Миколаєва загину...
242,"47.123866, 32.621648",9,July,Поранені цивільні,NaN,3.0,Через влучання по домогосподарствах у Широківс...
243,"46.959077, 32.011807",11,July,Поранені цивільні,NaN,1.0,У Миколаєві внаслідок ракетного обстрілу є оди...
244,"46.959077, 32.011807",12,July,Поранені цивільні,NaN,4.0,У Миколаєві через масований ракетний обстріл п...
245,"46.959077, 32.011807",14,July,Поранені цивільні,NaN,1.0,"По Миколаєву випущено 9 ракет типу С-300, пора..."
246,"46.999938, 32.395752",13,July,Поранені цивільні,NaN,2.0,Через обстріли с. Новоселівка поранено 2 людини.
247,"47.123866, 32.621648",15,July,Поранені цивільні,NaN,2.0,Через обстріли у Широківській громаді отримали...
248,"46.862150, 32.196443",16,July,Поранені цивільні,NaN,3.0,У с. Шевченкове внаслідок обстрілів поранені т...
249,"46.870032, 32.025611",18,July,Поранені цивільні,NaN,2.0,Окупанти обстріляли касетними снарядами Корабе...
250,"47.307953, 32.846669",20,July,Поранені цивільні,NaN,2.0,В смт Березнегувате після ракетного обстрілу з...
251,"46.959077, 32.011810",21,July,Поранені цивільні,NaN,1.0,Окупанти випустили по Миколаєву сім ракет С-30...
252,"46.959077, 32.011811",23,July,Поранені цивільні,NaN,5.0,По Миколаєву було випущено чотири крилатих рак...
253,"46.995222, 32.112717",25,July,Поранені цивільні,NaN,1.0,Через обстріл с. Мішково-Погорілове зазнала по...
254,"46.959077, 32.011812",28,July,Поранені цивільні,NaN,3.0,У Миколаєві через ворожий обстріл отримали пор...
255,"46.959077, 32.011812",29,July,Поранені цивільні,NaN,12.0,Ворожі касетні снаряди влучили у зупинку грома...
256,"46.959077, 32.011812",30,July,Поранені цивільні,NaN,6.0,У Миколаєві обстріляний один зі спальних район...
257,"46.959077, 32.011812",31,July,Поранені цивільні,NaN,2.0,Внаслідок масованих обстрілів Миколаєва поране...

In [12]:
df

,coordinates,day,month,sheet_name,type,scale,description
0,"46.959632, 32.006337",1,July,Ракети,NaN,NaN,NaN
1,"46.959077, 32.011807",1,July,Ракети,NaN,NaN,NaN
2,"46.959077, 32.011807",5,July,Ракети,NaN,NaN,NaN
3,"46.959077, 32.011807",11,July,Ракети,NaN,NaN,NaN
4,"46.959077, 32.011807",12,July,Ракети,NaN,NaN,NaN
...,...,...,...,...,...,...,...
415,"46.959077, 32.011810",18,July,Цивільна інфраструктура,point,NaN,У Миколаєві ракети влучили в автосалон та сало...
416,"47.041280, 32.438662",22,July,Цивільна інфраструктура,point,NaN,Влучання в будівлю магазину та гаражний коопер...
417,"46.959077, 32.011812",28,July,Цивільна інфраструктура,point,NaN,Ракетний удар по Миколаєву пошкодив яхт-клуб.
418,"46.959077, 32.011812",28,July,Цивільна інфраструктура,point,NaN,У Миколаєві пошкоджено пункт видачі гуманітарн...
419,"46.959077, 32.011812",31,July,Цивільна інфраструктура,point,NaN,Внаслідок масованих обстрілів Миколаєва пошкод...

In [13]:
df[['la', 'lo']] = df['coordinates'].str.split(',', 1, expand=True) #split column coordinates into two

/tmp/ipykernel_44754/1141815606.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['la', 'lo']] = df['coordinates'].str.split(',', 1, expand=True) #split column coordinates into two

In [14]:
del(df['coordinates']) #deleting coordinates column

In [15]:
#del(df['type']) #deleting type column

In [16]:
df['la'] = df['la'].astype(float) #assigning float to la and lo column

In [17]:
df['lo'] = df['lo'].astype(float)

In [18]:
df['day'] = df['day'].astype(int)

In [19]:
# froming date and unix timestamp columns
def date_convert(df):
    for i in range(len(df)):
    #for i in range(10):
        month = df['month'][1]
        s = month.strip()[:3] #strip to 3 letter
        m = strptime(s,'%b').tm_mon #getting month number
        #print(m)
        time = (f"2022-{m}-{df['day'][i]}")
        #print(time)
        df.loc[i,['date']] = time
        time_ms = pd.Timestamp(time).timestamp()
        df.loc[i,['timestamp']] = time_ms*1000

In [20]:
date_convert(df)

In [21]:
df.loc[50:65]

,day,month,sheet_name,type,scale,description,la,lo,date,timestamp
50,5,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.198526,32.829574,2022-7-5,1.656979e+12
51,4,July,Артилерія та РСЗВ,NaN,NaN,NaN,46.727960,31.972350,2022-7-4,1.656893e+12
52,5,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.123866,32.621648,2022-7-5,1.656979e+12
53,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.198526,32.829574,2022-7-6,1.657066e+12
54,5,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.023995,32.427847,2022-7-5,1.656979e+12
55,5,July,Артилерія та РСЗВ,NaN,NaN,NaN,46.606658,31.565892,2022-7-5,1.656979e+12
56,5,July,Артилерія та РСЗВ,NaN,NaN,NaN,46.659323,31.634256,2022-7-5,1.656979e+12
57,5,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.022603,32.455243,2022-7-5,1.656979e+12
58,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,46.942736,31.552642,2022-7-6,1.657066e+12
59,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,46.870032,32.025611,2022-7-6,1.657066e+12
60,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.123866,32.621648,2022-7-6,1.657066e+12
61,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.198526,32.829574,2022-7-6,1.657066e+12
62,5,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.198526,32.829574,2022-7-5,1.656979e+12
63,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,46.966356,32.359167,2022-7-6,1.657066e+12
64,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.090263,32.448873,2022-7-6,1.657066e+12
65,6,July,Артилерія та РСЗВ,NaN,NaN,NaN,47.041280,32.438662,2022-7-6,1.657066e+12

In [22]:
df.loc[[4]]

,day,month,sheet_name,type,scale,description,la,lo,date,timestamp
4,12,July,Ракети,NaN,NaN,NaN,46.959077,32.011807,2022-7-12,1.657584e+12

In [23]:
del(df['day'])
del(df['month'])

In [24]:
df['timestamp'][1]

1656633600000.0

In [25]:
df.loc[df['sheet_name'].isin(['Загиблі цивільні'])] #show begining of the second dataframe

,sheet_name,type,scale,description,la,lo,date,timestamp
227,Загиблі цивільні,NaN,1.0,"В с. Білозірка пошкоджено будинок, загинула од...",47.090263,32.448873,2022-7-1,1.656634e+12
228,Загиблі цивільні,NaN,1.0,В селищі Луч внаслідок ворожих обстрілів загин...,46.826064,32.219268,2022-7-2,1.656720e+12
229,Загиблі цивільні,NaN,1.0,Внаслідок обстрілів с. Засілля загинула одна л...,47.023995,32.427847,2022-7-5,1.656979e+12
230,Загиблі цивільні,NaN,1.0,Під час обстрілів с. Нечаяне загинула одна люд...,46.942736,31.552642,2022-7-6,1.657066e+12
231,Загиблі цивільні,NaN,2.0,Внаслідок обстрілів с. Українка Галицинівської...,46.824849,32.141298,2022-7-7,1.657152e+12
232,Загиблі цивільні,NaN,1.0,Через ракетний удар по Баштанці загинула жінка.,47.403720,32.438221,2022-7-12,1.657584e+12
233,Загиблі цивільні,NaN,4.0,Через обстріли с. Новоселівка загинуло 4 людини.,46.999938,32.395752,2022-7-13,1.657670e+12
234,Загиблі цивільні,NaN,1.0,Через нічний обстріл Баштанки загинула одна лю...,47.403720,32.438221,2022-7-14,1.657757e+12
235,Загиблі цивільні,NaN,3.0,У с. Шевченкове внаслідок обстрілів загинули т...,46.862150,32.196443,2022-7-16,1.657930e+12
236,Загиблі цивільні,NaN,1.0,Через обстріли у Широківській громаді загинула...,47.123866,32.621648,2022-7-16,1.657930e+12
237,Загиблі цивільні,NaN,1.0,В с. Широке внаслідок влучання боєприпасу в жи...,47.098634,32.674144,2022-7-21,1.658362e+12
238,Загиблі цивільні,NaN,2.0,Через удари по с. Шевченкове загинуло дві людини.,46.862150,32.196443,2022-7-23,1.658534e+12
239,Загиблі цивільні,NaN,7.0,Ворожі касетні снаряди влучили у зупинку грома...,46.959077,32.011812,2022-7-29,1.659053e+12
240,Загиблі цивільні,NaN,1.0,У Миколаєві обстріляли один зі спальних районі...,46.959077,32.011812,2022-7-30,1.659139e+12
241,Загиблі цивільні,NaN,1.0,Внаслідок масованих обстрілів Миколаєва загину...,46.959077,32.011812,2022-7-31,1.659226e+12

In [59]:
df.to_csv('july.csv', index=False)

In [62]:
df1 = df.loc[df['description'].isnull()] #show empty rows

In [63]:
df1 #split into dataframes with null description

,sheet_name,scale,description,la,lo,date,timestamp
0,Ракети,NaN,NaN,46.959632,32.006337,2022-07-1,1.656634e+09
1,Ракети,NaN,NaN,46.959077,32.011807,2022-07-1,1.656634e+09
2,Ракети,NaN,NaN,46.959077,32.011807,2022-07-5,1.656979e+09
3,Ракети,NaN,NaN,46.959077,32.011807,2022-07-11,1.657498e+09
4,Ракети,NaN,NaN,46.959077,32.011807,2022-07-12,1.657584e+09
...,...,...,...,...,...,...,...
222,Артилерія та РСЗВ,NaN,NaN,47.286823,33.071037,2022-07-31,1.659226e+09
223,Артилерія та РСЗВ,NaN,NaN,47.366277,33.062555,2022-07-31,1.659226e+09
224,Артилерія та РСЗВ,NaN,NaN,47.312209,32.985710,2022-07-31,1.659226e+09
225,Артилерія та РСЗВ,NaN,NaN,47.365991,32.940963,2022-07-31,1.659226e+09
226,Артилерія та РСЗВ,NaN,NaN,47.321430,32.910420,2022-07-31,1.659226e+09

In [64]:
df2 = df.loc[df['description'].notnull()] #show without rows

In [65]:
df2

,sheet_name,scale,description,la,lo,date,timestamp
227,Загиблі цивільні,1.0,"В селі Білозірка пошкоджено будинок, загинула ...",47.090263,32.448873,2022-07-1,1.656634e+09
228,Загиблі цивільні,1.0,В селищі Луч внаслідок ворожих обстрілів загин...,46.826064,32.219268,2022-07-2,1.656720e+09
229,Загиблі цивільні,1.0,Внаслідок обстрілів села Засілля загинула одна...,47.023995,32.427847,2022-07-5,1.656979e+09
230,Загиблі цивільні,1.0,Під час обстрілів с. Нечаяне одна людина загин...,46.942736,31.552642,2022-07-6,1.657066e+09
231,Загиблі цивільні,2.0,Внаслідок обстрілів села Українка Галицинівськ...,46.824849,32.141298,2022-07-7,1.657152e+09
...,...,...,...,...,...,...,...
415,Цивільна інфраструктура,NaN,У Миколаєві ракети влучили в автосалон та сало...,46.959077,32.011810,2022-07-18,1.658102e+09
416,Цивільна інфраструктура,NaN,Влучання в будівлю магазину та гаражний коопер...,47.041280,32.438662,2022-07-22,1.658448e+09
417,Цивільна інфраструктура,NaN,Ракетний удар по Миколаєву пошкодив яхт-клуб.,46.959077,32.011812,2022-07-28,1.658966e+09
418,Цивільна інфраструктура,NaN,У Миколаєві пошкоджено пункт видачі гуманітарн...,46.959077,32.011812,2022-07-28,1.658966e+09
419,Цивільна інфраструктура,NaN,Внаслідок масованих обстрілів Миколаєва пошкод...,46.959077,32.011812,2022-07-31,1.659226e+09

In [118]:
concatenated = pd.DataFrame() #create empty dataframe

In [120]:
concatenated = pd.concat([concatenated, df]) #concate multiple tables into one

In [27]:
# from here https://notebook.community/captainsafia/nteract/applications/desktop/example-notebooks/pandas-to-geojson
def df_to_geojson(df, properties, lat='la', lon='lo'):
    # create a new python dict to contain our geojson data, using geojson format
    geojson = {'type':'FeatureCollection', 'features':[]}

    # loop through each row in the dataframe and convert each row to geojson format
    for _, row in df.iterrows():
        # create a feature template to fill in
        feature = {'type':'Feature',
                   'properties':{},
                   'geometry':{'type':'Point',
                               'coordinates':[]}}

        # fill in the coordinates
        feature['geometry']['coordinates'] = [row[lon],row[lat]]

        # for each column, get the value and add it as a new feature property
        for prop in properties:
            feature['properties'][prop] = row[prop]
        
        # add this feature (aka, converted dataframe row) to the list of features inside our dict
        geojson['features'].append(feature)
    
    return geojson

In [32]:
cols = ['day', 'month', 'sheet_name']
geojson = df_to_geojson(df1, cols)

In [32]:
cols = ['day', 'month', 'sheet_name']
geojson = df_to_geojson(df1, cols)

In [25]:
with open('july_targets2.geojson', 'w', encoding='utf-8') as f:
    json.dump(geojson, f, ensure_ascii=False)

In [9]:
df_texty = pd.read_csv('../texty_map/Copy of fire_points - data_to_use.csv')

In [17]:
filtered_values = np.where((df_texty['Область'].str.startswith('Миколаїв')))
print(filtered_values)
new_df_texty = df_texty.loc[filtered_values]

(array([   95,   103,   104,   110,   225,   263,   264,   274,   319,
         322,   326,   443,   466,   467,   468,   473,   481,   482,
         487,   491,   537,   538,   639,   679,   680,   743,   744,
         759,   821,   870,   944,  1006,  1325,  1327,  1727,  1754,
        1764,  1765,  1766,  1771,  1772,  1909,  1934,  2013,  2016,
        2061,  2085,  2091,  2106,  2113,  2115,  2164,  2175,  2200,
        2235,  2296,  2360,  2417,  2418,  2431,  2447,  2448,  2465,
        2495,  2498,  2521,  2522,  2523,  2540,  2541,  2542,  2551,
        2588,  2589,  2590,  2591,  2592,  2633,  2634,  2635,  2636,
        2637,  2645,  2685,  2686,  2687,  2688,  2689,  2705,  2706,
        2757,  2759,  2774,  2794,  2837,  2838,  2839,  2868,  2869,
        2870,  2958,  2968,  3013,  3014,  3077,  3087,  3109,  3110,
        3111,  3112,  3113,  3126,  3127,  3148,  3149,  3150,  3151,
        3152,  3153,  3200,  3207,  3221,  3230,  3231,  3262,  3267,
        3275,  3294,  3312,  3313,  3359,  3360,  3361,  3362,  3363,
        3364,  3378,  3405,  3414,  3415,  3416,  3425,  3445,  3459,
        3496,  3559,  3560,  3561,  3562,  3566,  3584,  3585,  3607,
        3622,  3632,  3633,  3634,  3635,  3636,  3637,  3679,  3680,
        3681,  3682,  3683,  3684,  3710,  3711,  3714,  3737,  3756,
        3759,  3760,  3762,  3830,  3831,  3832,  3856,  3857,  3858,
        3859,  3881,  3882,  3883,  3921,  3940,  3941,  3942,  3980,
        3981,  3982,  3994,  4007,  4008,  4009,  4010,  4011,  4054,
        4055,  4056,  4057,  4058,  4059,  4061,  4074,  4075,  4076,
        4077,  4078,  4079,  4138,  4146,  4163,  4164,  4165,  4166,
        4177,  4178,  4179,  4180,  4183,  4193,  4201,  4202,  4223,
        4224,  4225,  4246,  4247,  4294,  4295,  4297,  4367,  4371,
        4372,  4373,  4374,  4377,  4382,  4410,  4412,  4414,  4415,
        4517,  4518,  4519,  4520,  4521,  4538,  4645,  4646,  4647,
        4691,  4692,  4732,  4733,  4857,  4858,  4933,  4934,  4936,
        4937,  4938,  4940,  4942,  4945,  4946,  4947,  4948,  4993,
        5030,  5031,  5032,  5034,  5115,  5117,  5119,  5120,  5122,
        5123,  5124,  5125,  5126,  5127,  5128,  5131,  5136,  5137,
        5138,  5139,  5140,  5167,  5168,  5169,  5170,  5179,  5229,
        5230,  5231,  5232,  5233,  5234,  5235,  5236,  5237,  5333,
        5334,  5335,  5358,  5359,  5360,  5361,  5362,  5402,  5403,
        5404,  5405,  5406,  5407,  5417,  5445,  5447,  5448,  5451,
        5452,  5453,  5454,  5455,  5456,  5553,  5568,  5569,  5596,
        5608,  5609,  5610,  5611,  5750,  5752,  5753,  5754,  5755,
        5756,  5757,  5758,  5759,  5760,  5761,  5763,  5764,  5777,
        5778,  5836,  5837,  5838,  5839,  5840,  5841,  5842,  5843,
        5844,  5870,  5871,  5872,  5873,  5874,  5875,  5922,  5923,
        5924,  5979,  5981,  5982,  5984,  5985,  5986,  5987,  5988,
        5989,  5990,  5991,  5992,  5993,  5994,  5995,  6010,  6011,
        6127,  6173,  6174,  6175,  6176,  6177,  6178,  6180,  6181,
        6182,  6183,  6270,  6271,  6272,  6273,  6274,  6275,  6276,
        6277,  6278,  6349,  6390,  6401,  6402,  6403,  6404,  6405,
        6406,  6407,  6464,  6465,  6466,  6467,  6468,  6470,  6471,
        6537,  6552,  6594,  6603,  6604,  6606,  6607,  6608,  6609,
        6667,  6734,  6743,  6753,  6754,  6755,  6756,  6757,  6759,
        6817,  6818,  6819,  6820,  6821,  6822,  6823,  6824,  6828,
        6859,  6871,  6949,  6950,  6951,  6954,  6955,  6956,  6957,
        6958,  6959,  6960,  6962,  6963,  6969,  7032,  7037,  7038,
        7047,  7087,  7088,  7142,  7177,  7178,  7179,  7180,  7181,
        7182,  7186,  7201,  7202,  7203,  7300,  7368,  7374,  7377,
        7434,  7435,  7439,  7440,  7474,  7533,  7535,  7536,  7537,
        7538,  7539,  7541,  7545,  7551,  7557,  7558,  7559,  7560,
        7561,  7564,  7609,  7610,  7611,  7612,  7613,  7614,  7704,
        7705,  7717,  7719,  7720,  7854,  7856,  7857,  7858,  7859,
        7861,  7862,  7863,  7864,  7867,  7877,  7878,  7879,  7941,
        7942,  7943,  7944,  7945,  7946,  7947,  7948,  7964,  8025,
        8026,  8027,  8029,  8030,  8031,  8032,  8034,  8044,  8045,
        8046,  8071,  8072,  8073,  8074,  8075,  8076,  8077,  8078,
        8079,  8080,  8081,  8082,  8083,  8084,  8085,  8086,  8087,
        8088,  8089,  8090,  8091,  8092,  8093,  8094,  8095,  8096,
        8113,  8114,  8115,  8116,  8117,  8119,  8120,  8121,  8122,
        8123,  8125,  8126,  8127,  8246,  8248,  8259,  8282,  8283,
        8284,  8387,  8388,  8389,  8390,  8391,  8392,  8393,  8394,
        8395,  8396,  8415,  8525,  8527,  8528,  8529,  8530,  8531,
        8532,  8548,  8553,  8554,  8584,  8585,  8587,  8687,  8736,
        8737,  8738,  8739,  8742,  8747,  8752,  8794,  8805,  8807,
        8867,  8934,  8935,  8938,  8941,  8946,  8947,  8948,  8951,
        9014,  9015,  9016,  9021,  9023,  9027,  9028,  9046,  9047,
        9048,  9053,  9112,  9113,  9231,  9240,  9242,  9243,  9245,
        9246,  9247,  9248,  9249,  9250,  9257,  9258,  9259,  9319,
        9320,  9379,  9380,  9381,  9383,  9384,  9385,  9386,  9391,
        9392,  9393,  9394,  9450,  9451,  9452,  9453,  9455,  9456,
        9457,  9458,  9459,  9460,  9461,  9462,  9463,  9464,  9465,
        9468,  9469,  9474,  9475,  9476,  9477,  9478,  9479,  9480,
        9481,  9482,  9483,  9485,  9491,  9587,  9588,  9589,  9590,
        9591,  9592,  9593,  9594,  9595,  9670,  9672,  9673,  9674,
        9676,  9678,  9753,  9754,  9755,  9756,  9757,  9758,  9759,
        9760,  9761,  9762,  9900,  9901,  9902,  9903,  9904,  9914,
        9915,  9916,  9917,  9919,  9920,  9921,  9922,  9923,  9999,
       10002, 10052, 10053, 10054, 10055, 10058, 10067, 10138, 10209,
       10212, 10213, 10214, 10215, 10216, 10288, 10293, 10294, 10295,
       10296, 10307, 10308, 10309, 10460, 10464, 10465, 10466, 10497,
       10543, 10544, 10545, 10546, 10547, 10548, 10549, 10550, 10553,
       10554, 10555, 10616, 10618, 10619, 10633, 10637, 10638, 10689,
       10690, 10691, 10692, 10760, 10761, 10762, 10773, 10851, 10852,
       10853, 10854, 10865, 11003, 11257, 11258, 11439, 11444, 11487,
       11488, 11490, 11498, 11499, 11508, 11509, 11552, 11657, 11705,
       11708, 11711, 11712, 11713, 11715, 11763, 11769, 11947, 12030,
       12052, 12053, 12054, 12084, 12088, 12093, 12100, 12109, 12116,
       12122, 12130, 12131, 12137, 12140, 12150, 12266, 12267, 12268,
       12269, 12294, 12304, 12305, 12309, 12336, 12353, 12415, 12427,
       12449, 12459, 12503, 12534, 12537, 12538, 12539, 12540, 12541,
       12542, 12543, 12544, 12545, 12546, 12547, 12548, 12549, 12550,
       12551, 12552, 12553, 12554, 12555, 12556, 12557, 12558, 12559,
       12560, 12561, 12562, 12563, 12564, 12565, 12566, 12567, 12568,
       12569, 12570, 12571, 12572, 12573, 12574, 12575, 12576, 12577,
       12578, 12579, 12580, 12581, 12582, 12583, 12584, 12585, 12586,
       12587, 12588, 12589, 12590, 12591, 12592, 12593, 12594, 12595,
       12596, 12597, 12598, 12599, 12600, 12601, 12602, 12603, 12604,
       12605, 12606, 12607, 12608, 12609, 12610, 12611, 12612, 12613,
       12614, 12615, 12616, 12617, 12618, 12619, 12620, 12621, 12622,
       12623, 12624, 12625, 12626, 12627, 12628, 12629, 12630, 12631,
       12632, 12633, 12765, 12841, 12842, 12931, 12932, 12933, 13012,
       13091, 13152, 13322, 13545, 14192, 14365, 15046, 15130, 15135,
       15136, 15320, 15326, 15472, 15629, 15714, 15719, 15720, 15721,
       16057, 16147, 16207, 16208, 16229, 16455, 16666, 16758, 16759,
       16760, 16926, 16927, 17372, 17560, 17611, 17673, 17947, 18021]),)

In [18]:
new_df.to_csv('texty_Mykolaiv.csv', index=False)

In [10]:
df_shell = pd.read_csv('../xls_datasets/df2.csv')

In [11]:
df_shell["scale"].fillna(1, inplace = True) #replace all null values in a colum

In [12]:
cond = df_shell['sheet_name'].str.endswith('цивільні')
print(df_shell[cond].to_string())

            sheet_name  scale                                                                                                                                                                                                                                                                                              description         la         lo        date      timestamp
0     Загиблі цивільні    1.0                                                                                                                                                                                                                                                 В с. Білозірка пошкоджено будинок, загинула одна людина.  47.090263  32.448873    2022-7-1  1656633600000
1     Загиблі цивільні    1.0                                                                                                                                                                                                                                          В селищі Луч внаслідок ворожих обстрілів загинула одна людина.   46.826064  32.219268    2022-7-2  1656720000000
2     Загиблі цивільні    1.0                                                                                                                                                                                                                                                     Внаслідок обстрілів с. Засілля загинула одна людина.  47.023995  32.427847    2022-7-5  1656979200000
3     Загиблі цивільні    1.0                                                                                                                                                                                                                                                       Під час обстрілів с. Нечаяне загинула одна людина.  46.942736  31.552642    2022-7-6  1657065600000
4     Загиблі цивільні    2.0                                                                                                                                                                                                                              Внаслідок обстрілів с. Українка Галицинівської громади загинуло дві людини.  46.824849  32.141298    2022-7-7  1657152000000
5     Загиблі цивільні    1.0                                                                                                                                                                                                                                                         Через ракетний удар по Баштанці загинула жінка.   47.403720  32.438221   2022-7-12  1657584000000
6     Загиблі цивільні    4.0                                                                                                                                                                                                                                                         Через обстріли с. Новоселівка загинуло 4 людини.  46.999938  32.395752   2022-7-13  1657670400000
7     Загиблі цивільні    1.0                                                                                                                                                                                                                                                      Через нічний обстріл Баштанки загинула одна людина.  47.403720  32.438221   2022-7-14  1657756800000
8     Загиблі цивільні    3.0                                                                                                                                                                                                                                                У с. Шевченкове внаслідок обстрілів загинули три людини.   46.862150  32.196443   2022-7-16  1657929600000
9     Загиблі цивільні    1.0                                                                                                                                                                                                                                                    Через обстріли у Широківській громаді загинула жінка.  47.123866  32.621648   2022-7-16  1657929600000
10    Загиблі цивільні    1.0                                                                                                                                                                                                                            В с. Широке внаслідок влучання боєприпасу в житловий будинок є один загиблий.  47.098634  32.674144   2022-7-21  1658361600000
11    Загиблі цивільні    2.0                                                                                                                                                                                                                                                        Через удари по с. Шевченкове загинуло дві людини.  46.862150  32.196443   2022-7-23  1658534400000
12    Загиблі цивільні    7.0                                                                                                                                                                                  Ворожі касетні снаряди влучили у зупинку громадського транспорту в Корабельному районі Миколаєва, загинуло 7 цивільних.  46.959077  32.011812   2022-7-29  1659052800000
13    Загиблі цивільні    1.0                                                                                                                                                                                                                             У Миколаєві обстріляли один зі спальних районів міста, одна людина загинула.  46.959077  32.011812   2022-7-30  1659139200000
14    Загиблі цивільні    1.0                                                                                                                                                                                                                                             Внаслідок масованих обстрілів Миколаєва загинула одна людина  46.959077  32.011812   2022-7-31  1659225600000
15   Поранені цивільні    3.0                                                                                                                                                                                                                          Через влучання по домогосподарствах у Широківській громаді поранено троє людей.  47.123866  32.621648    2022-7-9  1657324800000
16   Поранені цивільні    1.0                                                                                                                                                                                                                                             У Миколаєві внаслідок ракетного обстрілу є один поранений.\n  46.959077  32.011807   2022-7-11  1657497600000
17   Поранені цивільні    4.0                                                                                                                                                                                                                                           У Миколаєві через масований ракетний обстріл поранено 4 людей.  46.959077  32.011807   2022-7-12  1657584000000
18   Поранені цивільні    1.0                                                                                                                                                                                                                                          По Миколаєву випущено 9 ракет типу С-300, поранена одна людина.  46.959077  32.011807   2022-7-14  1657756800000
19   Поранені цивільні    2.0                                                                                                                                                                                                                                                         Через обстріли с. Новоселівка поранено 2 людини.  46.999938  32.395752   2022-7-13  1657670400000
20   Поранені цивільні    2.0                                                                                                                                                                                                                                       Через обстріли у Широківській громаді отримали поранення 2 людини.  47.123866  32.621648   2022-7-15  1657843200000
21   Поранені цивільні    3.0                                                                                                                                                                                                                                                У с. Шевченкове внаслідок обстрілів поранені три людини.   46.862150  32.196443   2022-7-16  1657929600000
22   Поранені цивільні    2.0                                                                                                                                                                                                   Окупанти обстріляли касетними снарядами Корабельний район Миколаєва - поранень зазнали двоє цивільних.  46.870032  32.025611   2022-7-18  1658102400000
23   Поранені цивільні    2.0                                                                                                                                                                                                                         В смт Березнегувате після ракетного обстрілу з-під завалів врятовано дві людини.  47.307953  32.846669   2022-7-20  1658275200000
24   Поранені цивільні    1.0                                                                                                                                                                                                                               Окупанти випустили по Миколаєву сім ракет С-300, одна людина постраждала.   46.959077  32.011810   2022-7-21  1658361600000
25   Поранені цивільні    5.0                                                                                                                                                                                      По Миколаєву було випущено чотири крилатих ракети типу «Калібр». Відомо про п‘ятьох поранених, серед них підліток.   46.959077  32.011811   2022-7-23  1658534400000
26   Поранені цивільні    1.0                                                                                                                                                                                                                                     Через обстріл с. Мішково-Погорілове зазнала поранень 7-річна дитина.  46.995222  32.112717   2022-7-25  1658707200000
27   Поранені цивільні    3.0                                                                                                                                                                                                                                          У Миколаєві через ворожий обстріл отримали поранення троє осіб.  46.959077  32.011812   2022-7-28  1658966400000
28   Поранені цивільні   12.0                                                                                                                                                                                 Ворожі касетні снаряди влучили у зупинку громадського транспорту в Корабельному районі Миколаєва, поранено 12 цивільних.  46.959077  32.011812   2022-7-29  1659052800000
29   Поранені цивільні    6.0                                                                                                                                                                                                                            У Миколаєві обстріляний один зі спальних районів міста, шість людей поранено.  46.959077  32.011812   2022-7-30  1659139200000
30   Поранені цивільні    2.0                                                                                                                                                                                                                                              Внаслідок масованих обстрілів Миколаєва поранено дві людини  46.959077  32.011812   2022-7-31  1659225600000
193   Загиблі цивільні    1.0                                                                                                                                                                                                                                             Внаслідок масованого обстрілу Миколаєва одна людина загинула  46.959077  32.011812    2022-8-5  1659657600000
194   Загиблі цивільні    1.0                                                                                                                                                                                                                                                       Через обстріл Березнегуватого загинула одна людина  47.307953  32.846669    2022-8-6  1659744000000
195   Загиблі цивільні    1.0                                                                                                                                                                                                                                                Внаслідок обстрілу села Галицинове було вбито одну людину  46.780528  31.952911    2022-8-7  1659830400000
196   Загиблі цивільні    1.0                                                                                                                                                                                                                                             Ввечері внаслідок обстрілів смт Березнегувате загинула жінка  47.307953  32.846669   2022-8-11  1660176000000
197   Загиблі цивільні    1.0                                                                                                                                                                                                                                                      Внаслідок обстрілів села Веселий Кут загинула жінка  47.155185  32.910984   2022-8-12  1660262400000
198   Загиблі цивільні    1.0                                                                                                                                                                                                                            Під обстріл потрапило смт Березнегувате. Внаслідок чого одна людина загинула   47.307953  32.846669   2022-8-16  1660608000000
199   Загиблі цивільні    1.0                                                                                                                                                                                                                                        Зафіксовані ворожі обстріли смт Первомайське одна людина загинула  47.041280  32.438662   2022-8-26  1661472000000
200   Загиблі цивільні    1.0                                                                                                                                                                                          Ворог здійснював обстріли Шевченківської громади. Внаслідок обстрілів у селищі Любомирівка одна людина загинула  47.187785  32.874432   2022-8-28  1661644800000
201   Загиблі цивільні    2.0                                                                                                                                                                                             Миколаїв зазнав масований обстріл шістнадцятьма зенітними ракетами С-300. Внаслідок чого дві людини загинуло  46.959077  32.011812   2022-8-29  1661731200000
202   Загиблі цивільні    1.0                                                                                                                                                                                                                                       Ворог обстріляв об’єкти інфраструктури Миколаєва. Є один загиблий   46.959077  32.011812   2022-8-30  1661817600000
203  Поранені цивільні    3.0                                                                                                                                                                                                                                              Внаслідок масованих обстрілів Миколаєва поранено три людини  46.959077  32.011812    2022-8-1  1659312000000
204  Поранені цивільні    1.0                                                                                                                                                                                                                                Внаслідок обстрілу Миколаєва був поранений охоронець одного з гуртожитків  46.959077  32.011812    2022-8-2  1659398400000
205  Поранені цивільні    1.0                                                                                                                                                                                                                                                        Через обстріли с. Галицинове поранено одну людину  46.780528  31.952911    2022-8-3  1659484800000
206  Поранені цивільні    2.0                                                                                                                                                                                                                                               Було обстріляно село Зоря, як наслідок поранено дві людини  46.896352  32.288157    2022-8-3  1659484800000
207  Поранені цивільні    3.0                                                                                                                                                                                                                                           В селі Парутине внаслідок обстрілу троє людей зазнали поранень  46.706472  31.896191    2022-8-4  1659571200000
208  Поранені цивільні   21.0                                                                                                                                                                                                            Внаслідок масованого обстрілу Миколаєва поранено двадцять одна, серед яких 13-річний підліток  46.959077  32.011812    2022-8-5  1659657600000
209  Поранені цивільні    2.0                                                                                                                                                                                                                                               Через ракетний обстріл Миколаєва важко поранені дві людини  46.959077  32.011812    2022-8-6  1659744000000
210  Поранені цивільні    1.0                                                                                                                                                                                                                                             Внаслідок обстрілів села Новомиколаєвка поранено одну людину  46.966356  32.359167    2022-8-7  1659830400000
211  Поранені цивільні    1.0                                                                                                                                                                                                                                                           Через обстріл Березнегуватого поранено 5 людей  47.307953  32.846669    2022-8-6  1659744000000
212  Поранені цивільні    3.0                                                                                                                                                                                                                          В Миколаєві поранено 3 людей через ворожі обстріли, серед них дівчинка 13 років  46.959077  32.011812   2022-8-10  1660089600000
213  Поранені цивільні    1.0                                                                                                                                                                                                                           У Миколаєві поранення отримала одна цивільна особа внаслідок ворожого обстрілу  46.959077  32.011812   2022-8-13  1660348800000

In [26]:
filtered_values = np.where((df_shell['sheet_name'].str.endswith('цивільні'))&(df_shell['date'].str.startswith('2022-8')))
print(filtered_values)
new_df = df_shell.loc[filtered_values]

(array([193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220, 221, 222, 223, 224, 225, 226, 227]),)

In [30]:
new_df.sort_values('la')

,sheet_name,scale,description,la,lo,date,timestamp
207,Поранені цивільні,3.0,В селі Парутине внаслідок обстрілу троє людей ...,46.706472,31.896191,2022-8-4,1659571200000
195,Загиблі цивільні,1.0,Внаслідок обстрілу села Галицинове було вбито ...,46.780528,31.952911,2022-8-7,1659830400000
217,Поранені цивільні,3.0,В результаті влучання касетних боєприпасів РСЗ...,46.780528,31.952911,2022-8-18,1660780800000
205,Поранені цивільні,1.0,Через обстріли с. Галицинове поранено одну людину,46.780528,31.952911,2022-8-3,1659484800000
225,Поранені цивільні,1.0,Ворог здійснював обстріли Шевченківської грома...,46.885644,32.227655,2022-8-28,1661644800000
206,Поранені цивільні,2.0,"Було обстріляно село Зоря, як наслідок поранен...",46.896352,32.288157,2022-8-3,1659484800000
224,Поранені цивільні,1.0,Під ворожими обстрілами були с. Оленівка та с-...,46.935270,32.305433,2022-8-27,1661558400000
193,Загиблі цивільні,1.0,Внаслідок масованого обстрілу Миколаєва одна л...,46.959077,32.011812,2022-8-5,1659657600000
216,Поранені цивільні,1.0,Місто зазнало обстрілів ракетами типу С-300. О...,46.959077,32.011812,2022-8-19,1660867200000
213,Поранені цивільні,1.0,У Миколаєві поранення отримала одна цивільна о...,46.959077,32.011812,2022-8-13,1660348800000
212,Поранені цивільні,3.0,В Миколаєві поранено 3 людей через ворожі обст...,46.959077,32.011812,2022-8-10,1660089600000
226,Поранені цивільні,24.0,Миколаїв зазнав масований обстріл шістнадцятьм...,46.959077,32.011812,2022-8-29,1661731200000
209,Поранені цивільні,2.0,Через ракетний обстріл Миколаєва важко поранен...,46.959077,32.011812,2022-8-6,1659744000000
208,Поранені цивільні,21.0,Внаслідок масованого обстрілу Миколаєва поране...,46.959077,32.011812,2022-8-5,1659657600000
227,Поранені цивільні,2.0,Ворог обстріляв об’єкти інфраструктури Миколає...,46.959077,32.011812,2022-8-30,1661817600000
203,Поранені цивільні,3.0,Внаслідок масованих обстрілів Миколаєва поране...,46.959077,32.011812,2022-8-1,1659312000000
202,Загиблі цивільні,1.0,Ворог обстріляв об’єкти інфраструктури Миколає...,46.959077,32.011812,2022-8-30,1661817600000
201,Загиблі цивільні,2.0,Миколаїв зазнав масований обстріл шістнадцятьм...,46.959077,32.011812,2022-8-29,1661731200000
204,Поранені цивільні,1.0,Внаслідок обстрілу Миколаєва був поранений охо...,46.959077,32.011812,2022-8-2,1659398400000
210,Поранені цивільні,1.0,Внаслідок обстрілів села Новомиколаєвка поране...,46.966356,32.359167,2022-8-7,1659830400000
199,Загиблі цивільні,1.0,Зафіксовані ворожі обстріли смт Первомайське о...,47.041280,32.438662,2022-8-26,1661472000000
218,Поранені цивільні,3.0,Касетними снарядами обстріляно смт Первомайськ...,47.041280,32.438662,2022-8-19,1660867200000
215,Поранені цивільні,1.0,Внаслідок ворожих обстрілів в с. Червоне Воскр...,47.060660,32.376822,2022-8-17,1660694400000
197,Загиблі цивільні,1.0,Внаслідок обстрілів села Веселий Кут загинула ...,47.155185,32.910984,2022-8-12,1660262400000
219,Поранені цивільні,1.0,"Було обстріляно с. Любомирівка, одна людина за...",47.187785,32.874432,2022-8-20,1660953600000
200,Загиблі цивільні,1.0,Ворог здійснював обстріли Шевченківської грома...,47.187785,32.874432,2022-8-28,1661644800000
214,Поранені цивільні,1.0,Під обстріл потрапило смт Березнегувате. Внасл...,47.307953,32.846669,2022-8-16,1660608000000
198,Загиблі цивільні,1.0,Під обстріл потрапило смт Березнегувате. Внасл...,47.307953,32.846669,2022-8-16,1660608000000
211,Поранені цивільні,1.0,Через обстріл Березнегуватого поранено 5 людей,47.307953,32.846669,2022-8-6,1659744000000
223,Поранені цивільні,1.0,Обстрілів зазнало смт Березнегувате. Поранення...,47.307953,32.846669,2022-8-26,1661472000000
196,Загиблі цивільні,1.0,Ввечері внаслідок обстрілів смт Березнегувате ...,47.307953,32.846669,2022-8-11,1660176000000
194,Загиблі цивільні,1.0,Через обстріл Березнегуватого загинула одна лю...,47.307953,32.846669,2022-8-6,1659744000000
221,Поранені цивільні,1.0,Ворог обстріляв місто Баштанка. У результаті ч...,47.403720,32.438221,2022-8-21,1661040000000
220,Поранені цивільні,14.0,Був нанесений ракетою типу «Калібр» по місту В...,47.569273,31.332095,2022-8-20,1660953600000
222,Поранені цивільні,9.0,Були обстріли м. Новий Буг. Внаслідок цього 9 ...,47.690774,32.516459,2022-8-24,1661299200000

In [14]:
df_shell.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 735 entries, 0 to 734
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sheet_name   735 non-null    object
 1   scale        735 non-null    float64
 2   description  735 non-null    object
 3   la           735 non-null    float64
 4   lo           735 non-null    float64
 5   date         735 non-null    object
 6   timestamp    735 non-null    int64
dtypes: float64(3), int64(1), object(3)
memory usage: 40.3+ KB

In [28]:
cols = ['sheet_name', 'scale', 'description', 'date', 'timestamp']
geojson = df_to_geojson(df_shell, cols)

In [30]:
with open('../data3_withScale.geojson', 'w', encoding='utf-8') as f:
    json.dump(geojson, f, ensure_ascii=False)